<?php
/**
 * eelKit Framework
 * Copyright (c) 2026 James Elstone
 * Licensed under the BSD 3-Clause License
 * See LICENSE file for details.
 */
declare(strict_types=1);

// Automatic Class Loader
require_once __DIR__ . DIRECTORY_SEPARATOR . 'classes' . DIRECTORY_SEPARATOR . 'bootstrap.php';

$appName = trim((string)AppConfigurationStore::get('app_name', 'eelKit Framework'));
if ($appName === '') {
    $appName = 'eelKit Framework';
}

$appStrapline = AppConfigurationStore::appStrapline();

// *****************************
//  Process variables passed in
// *****************************

// Get http request details
$request = RequestFramework::fromGlobals();
$antiFraudService = AntiFraudService::instance($request);

// **********************
//  Setup Server Session
// **********************

// Start Session Service
$sessionAuthenticationService = new SessionAuthenticationService(request: $request);

// Start a server sided session
$sessionAuthenticationService->startSession();

// Start a session management service
$userSessionService = new UserSessionService();

// The remote device id (generated by js in the browser)
$currentDeviceId = trim((string)$antiFraudService->requestValue('Client-Device-ID'));


// *********************
//  User Authentication
// *********************

// Check existing session against device id, and log out current user if different device
$sessionAuthenticationService->invalidateForDeviceMismatch($currentDeviceId);

// Get user id for logged on user, 0 for unauthenticated
$authenticatedUserId = $sessionAuthenticationService->authenticatedUserId($currentDeviceId);

// Do we have a valid user id?
if ($authenticatedUserId > 0) {
    $sessionValidation = $userSessionService->validateAuthenticatedSession(
        $authenticatedUserId,
        $sessionAuthenticationService->authenticatedSessionTokenHash(),
        $currentDeviceId
    );

    if (empty($sessionValidation['valid'])) {
        $sessionAuthenticationService->logout((array)($sessionValidation['logout_notice'] ?? []));
    }
}

$authPageRenderer = new AuthPageRenderer($appName, $appStrapline);
$pageRequestGuard = new PageRequestGuard($appName, $authPageRenderer);

$ajaxNonceResponse = $pageRequestGuard->ajaxNonceResponse(
    $request,
    $sessionAuthenticationService,
    $currentDeviceId
);

if ($ajaxNonceResponse instanceof ResponseFramework) {
    $ajaxNonceResponse->send();
    return;
}

// Load User Authentication Service
$userAuthenticationService = new UserAuthenticationService();

// Start Login Service
$loginService = new LoginService(
    $userAuthenticationService,
    new OtpService($appName),
    new QrCodeService(),
    $sessionAuthenticationService,
    $userSessionService,
    new UserHistoryStore()
);

$firstUserBootstrapService = new FirstUserBootstrapService($appName);

// First user check
$requiresInitialUserSetup = $authenticatedUserId <= 0 && !$userAuthenticationService->hasAnyUsers();

// Do we have a first user code on the file system?
$bootstrapState = $requiresInitialUserSetup ? $firstUserBootstrapService->codeState() : null;

$authController = new AuthController(
    $loginService,
    $sessionAuthenticationService,
    $userAuthenticationService,
    $firstUserBootstrapService,
    $authPageRenderer
);

// Check for logon flow response to be sent, or null if already authenticated
$authResponse = $authController->response(
    $request,
    $currentDeviceId,
    $requiresInitialUserSetup,
    $bootstrapState
);

// Send authentication flow if unauthenticated (null)
if ($authResponse instanceof ResponseFramework) {
    $authResponse->send();
    return;
}

// *************************************
//  Load page, cards and create context
// *************************************

// Create new page factory
$pageFactory = new PageFactoryFramework();

// Reject pages disabled by application policy before loading the page class.
$requestedPageKey = $request->getPage();
$pageAccessPolicyResponse = $pageRequestGuard->pagePolicyResponse($request, $requestedPageKey);

if ($pageAccessPolicyResponse instanceof ResponseFramework) {
    $pageAccessPolicyResponse->send();
    return;
}

// Load page
$page = $pageFactory->create($requestedPageKey);

// Check if the user is allowed to see the page
$pageAccessResponse = $pageRequestGuard->pageAccessResponse(
    $request,
    $page,
    $sessionAuthenticationService,
    $currentDeviceId
);

// If they dont have valid permissions, show the access error
if ($pageAccessResponse instanceof ResponseFramework) {
    $pageAccessResponse->send();
    return;
}

// Load application config settings
$uploadBasePath = (string)(AppConfigurationStore::get('uploads.upload_base_dir') ?? '');

// Load services required by pages and cards
$appServices = new AppService($uploadBasePath);
$pageServices = new PageServiceFramework($appServices);

// Call the page / card(s) html renderer
$response = $page->handle($request, $pageServices);

// Send page and cards back to the client.
$response->send();

// == EOL ==
// ================================================================================
