<?php
/**
 * eelKit Framework
 * Copyright (c) 2026 James Elstone
 * Licensed under the BSD 3-Clause License
 * See LICENSE file for details.
 */
declare(strict_types=1);

// Automatic Class Loader
require_once __DIR__ . DIRECTORY_SEPARATOR . 'classes' . DIRECTORY_SEPARATOR . 'bootstrap.php';

const EEL_INDEX_HTML_COPYRIGHT_HEADER = '<!-- eelKit Framework - Copyright (c) 2026 James Elstone - Licensed under the BSD 3-Clause License - See LICENSE file for details. -->';
const EEL_INDEX_PROJECT_STYLESHEET_PATH = __DIR__ . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR . 'project.css';
const EEL_INDEX_PROJECT_STYLESHEET_LINK = '<link rel="stylesheet" href="css/project.css">';
const EEL_INDEX_PROJECT_SCRIPT_PATH = __DIR__ . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR . 'project.js';
const EEL_INDEX_PROJECT_SCRIPT_TAG = '<script src="js/project.js"></script>';

function eel_index_send_response(ResponseFramework $response): void
{
    if (stripos($response->contentType(), 'text/html') !== 0) {
        $response->send();
        return;
    }

    ob_start();
    $response->send();
    $html = (string)ob_get_clean();

    echo eel_index_html_with_project_script(
        eel_index_html_with_project_stylesheet(eel_index_html_with_copyright_header($html))
    );
}

function eel_index_html_with_copyright_header(string $html): string
{
    if (str_contains($html, EEL_INDEX_HTML_COPYRIGHT_HEADER)) {
        return $html;
    }

    $htmlWithHeader = preg_replace(
        '/(<!DOCTYPE html>)/i',
        '$1' . PHP_EOL . EEL_INDEX_HTML_COPYRIGHT_HEADER,
        $html,
        1
    );

    if (is_string($htmlWithHeader) && $htmlWithHeader !== $html) {
        return $htmlWithHeader;
    }

    return EEL_INDEX_HTML_COPYRIGHT_HEADER . PHP_EOL . $html;
}

function eel_index_html_with_project_stylesheet(string $html): string
{
    if (!is_file(EEL_INDEX_PROJECT_STYLESHEET_PATH)) {
        return $html;
    }

    if (preg_match('/<link\b[^>]*\bhref=(["\'])\/?css\/project\.css\1/i', $html) === 1) {
        return $html;
    }

    $htmlWithProjectStylesheet = preg_replace_callback(
        '/([ \t]*)<\/head>/i',
        static fn(array $matches): string => $matches[1] . EEL_INDEX_PROJECT_STYLESHEET_LINK
            . PHP_EOL
            . $matches[1] . '</head>',
        $html,
        1
    );

    if (is_string($htmlWithProjectStylesheet) && $htmlWithProjectStylesheet !== $html) {
        return $htmlWithProjectStylesheet;
    }

    return $html;
}

function eel_index_html_with_project_script(string $html): string
{
    if (!is_file(EEL_INDEX_PROJECT_SCRIPT_PATH)) {
        return $html;
    }

    if (preg_match('/<script\b[^>]*\bsrc=(["\'])\/?js\/project\.js\1/i', $html) === 1) {
        return $html;
    }

    $htmlWithProjectScript = preg_replace_callback(
        '/([ \t]*)<\/body>/i',
        static fn(array $matches): string => $matches[1] . EEL_INDEX_PROJECT_SCRIPT_TAG
            . PHP_EOL
            . $matches[1] . '</body>',
        $html,
        1
    );

    if (is_string($htmlWithProjectScript) && $htmlWithProjectScript !== $html) {
        return $htmlWithProjectScript;
    }

    return $html;
}

$appName = trim((string)AppConfigurationStore::get('app_name', 'eelKit Framework'));
if ($appName === '') {
    $appName = 'eelKit Framework';
}

$appStrapline = AppConfigurationStore::appStrapline();

// *****************************
//  Process variables passed in
// *****************************

// Get http request details
$request = RequestFramework::fromGlobals();
$antiFraudService = AntiFraudService::instance($request);

// **********************
//  Setup Server Session
// **********************

// Start Session Service
$sessionAuthenticationService = new SessionAuthenticationService(request: $request);

// Start a server sided session
$sessionAuthenticationService->startSession();

// Start a session management service
$userSessionService = new UserSessionService();

// The remote device id (generated by js in the browser)
$currentDeviceId = trim((string)$antiFraudService->requestValue('Client-Device-ID'));


// *********************
//  User Authentication
// *********************

// Check existing session against device id, and log out current user if different device
$sessionAuthenticationService->invalidateForDeviceMismatch($currentDeviceId);

// Get user id for logged on user, 0 for unauthenticated
$authenticatedUserId = $sessionAuthenticationService->authenticatedUserId($currentDeviceId);

// Do we have a valid user id?
if ($authenticatedUserId > 0) {
    $sessionValidation = $userSessionService->validateAuthenticatedSession(
        $authenticatedUserId,
        $sessionAuthenticationService->authenticatedSessionTokenHash(),
        $currentDeviceId
    );

    if (empty($sessionValidation['valid'])) {
        $sessionAuthenticationService->logout((array)($sessionValidation['logout_notice'] ?? []));
    }
}

$authPageRenderer = new AuthPageRenderer($appName, $appStrapline);
$pageRequestGuard = new PageRequestGuard($appName, $authPageRenderer);

$ajaxNonceResponse = $pageRequestGuard->ajaxNonceResponse(
    $request,
    $sessionAuthenticationService,
    $currentDeviceId
);

if ($ajaxNonceResponse instanceof ResponseFramework) {
    eel_index_send_response($ajaxNonceResponse);
    return;
}

// Load User Authentication Service
$userAuthenticationService = new UserAuthenticationService();

// Start Login Service
$loginService = new LoginService(
    $userAuthenticationService,
    new OtpService($appName),
    new QrCodeService(),
    $sessionAuthenticationService,
    $userSessionService,
    new UserHistoryStore()
);

$firstUserBootstrapService = new FirstUserBootstrapService($appName);

// First user check
$requiresInitialUserSetup = $authenticatedUserId <= 0 && !$userAuthenticationService->hasAnyUsers();

// Do we have a first user code on the file system?
$bootstrapState = $requiresInitialUserSetup ? $firstUserBootstrapService->codeState() : null;

$authController = new AuthController(
    $loginService,
    $sessionAuthenticationService,
    $userAuthenticationService,
    $firstUserBootstrapService,
    $authPageRenderer
);

// Check for logon flow response to be sent, or null if already authenticated
$authResponse = $authController->response(
    $request,
    $currentDeviceId,
    $requiresInitialUserSetup,
    $bootstrapState
);

// Send authentication flow if unauthenticated (null)
if ($authResponse instanceof ResponseFramework) {
    eel_index_send_response($authResponse);
    return;
}

// *************************************
//  Load page, cards and create context
// *************************************

// Create new page factory
$pageFactory = new PageFactoryFramework();

// Reject pages disabled by application policy before loading the page class.
$requestedPageKey = $request->getPage();
$pageAccessPolicyResponse = $pageRequestGuard->pagePolicyResponse($request, $requestedPageKey);

if ($pageAccessPolicyResponse instanceof ResponseFramework) {
    eel_index_send_response($pageAccessPolicyResponse);
    return;
}

// Load page
$page = $pageFactory->create($requestedPageKey);

// Check if the user is allowed to see the page
$pageAccessResponse = $pageRequestGuard->pageAccessResponse(
    $request,
    $page,
    $sessionAuthenticationService,
    $currentDeviceId
);

// If they dont have valid permissions, show the access error
if ($pageAccessResponse instanceof ResponseFramework) {
    eel_index_send_response($pageAccessResponse);
    return;
}

// Load application config settings
$uploadBasePath = (string)(AppConfigurationStore::get('uploads.upload_base_dir') ?? '');

// Load services required by pages and cards
$appServices = new AppService($uploadBasePath);
$pageServices = new PageServiceFramework($appServices);
$pageServices->setSiteContextCoordinator(SiteContextCoordinatorFramework::fromConfiguration($appServices));

// Call the page / card(s) html renderer
$response = $page->handle($request, $pageServices);

// Send page and cards back to the client.
eel_index_send_response($response);

// == EOL ==
// ================================================================================
